# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=120, null=True)),
                ('city', models.CharField(max_length=120, null=True)),
                ('street', models.CharField(max_length=120, null=True)),
                ('postal_code', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, null=True, unique=True)),
                ('last_name', models.CharField(max_length=120, null=True)),
                ('email', models.EmailField(max_length=30, null=True, unique=True)),
                ('description', models.TextField(default='description default')),
                ('role', models.CharField(choices=[('Customer', 'customer'), ('Sales person', 'sales person'), ('Manager', 'manager')], default='User', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='shopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('quantity', models.CharField(max_length=120, null=True)),
                ('price', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, unique=True)),
                ('last_name', models.CharField(max_length=120, null=True)),
                ('email', models.EmailField(max_length=30, null=True, unique=True)),
            ],
        ),
    ]
