# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171019_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
