# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_admin_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Customer', 'customer'), ('Sales person', 'sales person'), ('Manager', 'manager')], default='User', max_length=30),
        ),
    ]
