# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171019_1256'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Apiuser',
        ),
    ]
