# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171020_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='postal_code',
            new_name='postalcode',
        ),
        migrations.AddField(
            model_name='apiuser',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Address'),
        ),
    ]
