# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171023_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='password',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
