# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20171027_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(max_length=120),
        ),
    ]
