# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20171027_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='invoice_id',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(),
        ),
    ]
