# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20171027_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='role',
            field=models.CharField(choices=[('Customer', 'customer'), ('Sales person', 'sales person'), ('Manager', 'manager'), ('Admin', 'admin')], default='User', max_length=30),
        ),
    ]
