# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-02 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20171030_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='role',
            field=models.CharField(choices=[('Customer', 'customer'), ('Sales person', 'sales person'), ('Manager', 'manager'), ('Admin', 'admin'), ('User', 'user')], default='User', max_length=30),
        ),
    ]
