version: '3'

services:
  db:
    image: postgres
    # env_file: postgres.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - net-tier

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - backend
      - frontend
    volumes:
      - ./backend/static:/static
    ports:
      - "80:80"
    networks:
      - net-tier

  backend:
    depends_on:
      - db
    build: ./backend
    command: bash -c "python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/project
    ports:
      - "8000:8000"
    networks:
      - net-tier

  frontend:
    depends_on:
      - backend
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend/src:/project/src
      - ./frontend/dist:/project/dist
      - ./frontend/test:/project/test
    ports:
      - "8080:8080"
    networks:
      - net-tier

networks:
  net-tier:
    driver: bridge
